### ISSUE TITLE
Text-Only Button Text Not Centered Vertically

### ISSUE THREAD

**Issue by jacobgraf** [verbb/buttonbox#10]
I'm curious about the 2px top-margin applied to button labels? It's causing the text to be off-center vertically...

![text-before](https://cloud.githubusercontent.com/assets/146333/15445432/1b42d9da-1ec4-11e6-9e63-c0d3a3c4d633.jpg)

If I remove the 2px, everything looks great...

![text-after](https://cloud.githubusercontent.com/assets/146333/15445439/2a39f202-1ec4-11e6-904f-b76917b120bf.jpg)

**Comment by engram-design** [comment]
Closing due to age (also seems no longer to be an issue)
