### ISSUE TITLE
Button Box toggle breaks if switching Entry Types multiple times

### ISSUE THREAD

**Issue by johndwells** [verbb/buttonbox#12]
I'm using a Button Box field in one of a couple Entry Types assigned to the Section, and it's not the default Entry Type - so to see the BB field in action I first have to switch Entry Types.  Upon the first switch, the BB field works fine and I can toggle the button selection; however if I change back to the first Entry Type, and then _back_ to the Entry Type with the BB field, I can no longer change it, it remains "stuck" on whatever the value currently is.

**Comment by joshangell** [comment]
Thanks for reporting this John, I can’t promise when I'll get to look at it but I will try!

**Comment by engram-design** [comment]
Can't replicate this, but closing due to the age of the issue.
