### ISSUE TITLE
long dropdowns does not work

### ISSUE THREAD

**Issue by supercooljames** [verbb/buttonbox#13]
_Via Felix Stößel …_

> Hello,
> 
> we are using Button Box and when a dropdown is very long and on Live Preview, we've got the problem that this dropdown isn't a native element (that can overflow the browser window boundaries), so I don't have the option to scroll this dropdown.
> 
> Here is a screencast I did:
> https://ufile.io/hjp9u
> 
> A solution would be to check via some isInViewPort methods if the whole dropdown is visible, if not, make it scrollable. These functions may be helpful: https://jsfiddle.net/qx7sdxee/
> 
> Best wishes
> Felix Stößel

**Comment by engram-design** [comment]
Closing due to age and links no longer working.
