### ISSUE TITLE
C2->C3 Upgrade - fields/data not migrating?

### ISSUE THREAD

**Issue by michaelroper** [verbb/buttonbox#20]
Hey guys,

Just upgrading a site from Craft v2 to v3, and having an issue where the fieldtype/data seems to not be migrating.
Initial state:
![image](https://user-images.githubusercontent.com/60287/40408267-8820c956-5e99-11e8-8000-86b84606000b.png)

The new fieldtype is available to select, and indicates that I won't lose data by changing, but when I select it, no data seems to have been migrated?

After selecting fieldtype:
![image](https://user-images.githubusercontent.com/60287/40408338-c3e21238-5e99-11e8-984e-2560f68f7575.png)

Any ideas? Did the fieldtype name change between versions?

**Comment by bossanova808** [comment]
It looks to me as if we're gonna have to change these fields manually - or did you find a solution to this at all?  

I presume manually changing the fields to the equivalent new types will keep all the data in tact but it would be nice to be sure...

But what is bothersome is that I presume I will need to do this every time I import a C2 database to C3 along my development cycle.

Really feels like there should be a migration here to take care of this...

**Comment by michaelroper** [comment]
Awesome Jeremy, top work! 
Sorry I didn't get to replying to your question, but no, I hadn't got around to find a solution, so this will be helpful!

**Comment by bossanova808** [comment]
No probs.

So I made this into a console command because I am going to have to do this a number of times.  You can see it here and adapt as you need to... (this does a bit more - it forces the install of some plugins that are marked not installed after my C2 -> C3 update, for whatever reason, and then migrates those fields that are missing a migration and (if needed) updates their settings too..)

https://gist.github.com/bossanova808/b30a643f28b8125d7a32c46df9da6044

**Comment by j-greig** [comment]
@bossanova808 Is your console command available anywhere else? That link seems to be dead now... I just migrated from C2 to C3 and ButtonBox fields all seem to have lost their values : (

**Comment by bossanova808** [comment]
Sorry, must have deleted the gist. In a nutshell, what you need is:

```
        print("Running Field Type Migrations (...that plugin authors have neglected to provide!)\n");

        //SUPERCOOL BUTTON BOX FIELDS

        $db = Craft::$app->getDb();

        print("Button Box fields\n");

        $count = $db->createCommand()->update('{{%fields}}', [
            'type' => ColoursField::class
        ], ['type' => 'ButtonBox_Colours'])->execute();

        $count += $db->createCommand()->update('{{%fields}}', [
            'type' => ButtonsField::class
        ], ['type' => 'ButtonBox_Buttons'])->execute();

        $count += $db->createCommand()->update('{{%fields}}', [
            'type' => WidthField::class
        ], ['type' => 'ButtonBox_Width'])->execute();

        print("$count rows affected\n");
```

**Comment by Mosnar** [comment]
@bossanova808 Thanks for that! Here's the same thing updated as migration you can run in Craft (under utilities).

Create a new file in the Craft root in the `migrations` folder called: `m190506_031734_migrate_buttonbox.php`

```php
<?php

namespace craft\contentmigrations;

use Craft;
use craft\db\Migration;
use supercool\buttonbox\fields\Colours;
use supercool\buttonbox\fields\Buttons;
use supercool\buttonbox\fields\Width;

/**
 * m190506_031734_migrate_buttonbox migration.
 */
class m190506_031734_migrate_buttonbox extends Migration
{
    /**
     * @inheritdoc
     */
    public function safeUp()
    {
        $db = Craft::$app->getDb();

        $count = $db->createCommand()->update('{{%fields}}', [
            'type' => Colours::class
        ], ['type' => 'ButtonBox_Colours'])->execute();

        $count += $db->createCommand()->update('{{%fields}}', [
            'type' => Buttons::class
        ], ['type' => 'ButtonBox_Buttons'])->execute();

        $count += $db->createCommand()->update('{{%fields}}', [
            'type' => Width::class
        ], ['type' => 'ButtonBox_Width'])->execute();
    }

    /**
     * @inheritdoc
     */
    public function safeDown()
    {
        echo "m190506_031734_migrate_buttonbox cannot be reverted.\n";
        return false;
    }
}

```

**Comment by j-greig** [comment]
Many many thanks @bossanova808 @Mosnar, just ran the above through Utilities->Migrations and it worked perfectly :)

**Comment by iamjamie** [comment]
@bossanova808 @Mosnar Cheers guys, saved me a headache!

**Comment by engram-design** [comment]
Thanks for sending this through @bossanova808 and @Mosnar this probably is way past useful at this point with most people updated from Craft 2, but still adding it for the next release.

**Comment by engram-design** [comment]
Added in [3.0.1](https://github.com/verbb/buttonbox/releases/tag/3.0.1)
