### ISSUE TITLE
TypeError in passing value from colour fields

### ISSUE THREAD

**Issue by i-hardy** [verbb/buttonbox#22]
I'm working on a highly user-customisable Craft-based site at the moment and this plugin is fantastic, thank you! However attempting to save an entry that has a colour field in it throws the following error:

```
TypeError
Argument 1 passed to craft\fields\BaseOptionsField::optionLabel() must be of the type string, array
given, called in /Users/path/to/repo/site/vendor/supercool/buttonbox/src/fields/Colours.php on line
100
```

This happened both when creating fields from scratch and converting basic Craft dropdowns. The fields were always in the context of a matrix or Neo block. I tried creating a test colour field and adding it to a section on its own, and the entry type wouldn't save at all.

I haven't encountered any issues with the other Buttonbox field types I'm using. I'm running Craft 3.0.15 and Buttonbox 2.0.1.

**Comment by SanboKyo** [comment]
The same issue in my case since I updated Craft to the newest version.

A workaround: comment line 99 in /vendor/supercool/buttonbox/src/fields/Colours.php

`//$value = reset($selectedValues) ?: null;`

**Comment by Nav33d** [comment]
@i-hardy @SanboKyo Could you please let me know the version of PHP you are using? As it seems to work fine when using PHP 7.0

**Comment by SanboKyo** [comment]
@Nav33d  I tested it again...

With PHP 7.1 I get the same error as i-hardy, see above.

With PHP 7.2 there is no error with colours field, but with buttons field:

> count(): Parameter must be an array or an object that implements Countable
> ...
> 3. in /Applications/MAMP/htdocs/achtung/vendor/craftcms/cms/src/base/Element.php at line 1082 – supercool\buttonbox\fields\Buttons::isValueEmpty()

**Comment by i-hardy** [comment]
@Nav33d I'm running 7.0.2 on MAMP.

**Comment by i-hardy** [comment]
After updating to Buttonbox 2.0.2 I started seeing the same error when trying to save text size fields as well- happened with both Craft 3.0.15 and 3.0.16.

**Comment by Nav33d** [comment]
@i-hardy Are you still seeing these errors? I have just tested using PHP 7.0 and 7.2 with Craft 3.0.18 and it all seems to work fine here.

**Comment by wooge** [comment]
Similar issue here using Width Widget and PHP 7.1.x, Craft 3.0.31, Button Box 2.0.2

**Comment by SanboKyo** [comment]
Unfortunately not! Last commit was on Jul 13, 2018.

Maybe my workaround will work also in your case: 

comment line 99 in /vendor/supercool/buttonbox/src/fields/Colours.php
//$value = reset($selectedValues) ?: null;

**Comment by engram-design** [comment]
Cannot replicate this on the latest versions. Please comment if this is an issue.
