### ISSUE TITLE
Button Box - when 0 as value, default value is applied

### ISSUE THREAD

**Issue by olsp** [verbb/buttonbox#23]
I'm using a button box and have values from 0 to 20. When I set 6 as default value for the field and then choose 0 as actual value, the default value is applied.

**Comment by Nav33d** [comment]
@olsp Could you please let me know the field you are using?

**Comment by Nav33d** [comment]
@olsp Yes its because 0 evaluates to false which then sets the default value. Could you please use letters as values like `zero`, `one` and so on. 

Many thanks

**Comment by olsp** [comment]
But does it make sense to have a "false" value in a width field?

**Comment by wooge** [comment]
Maybe instead of "false" it's "null" if there is nothing set.
