### ISSUE TITLE
3.1 beta migration error: "Getting unknown property"

### ISSUE THREAD

**Issue by michaelroper** [verbb/buttonbox#26]
Hey super cool people!

I've run into an issue with the ButtonBox plugin (`v2.0.2`) when trying to update to the latest version of the Craft 3.1 beta. It's working fine on versions up to `3.1.0-beta.5.1`, but anything after that, like the latest `3.1.0-beta.7` release, it will fail with the following error when trying to run the `./craft migrate/all` command.

```
Exception: Getting unknown property: supercool\buttonbox\fields\Buttons::contentTable (/Users/michael.roper/Sites/v-website/vendor/yiisoft/yii2/base/Component.php:154)
#0 /Users/michael.roper/Sites/v-website/vendor/craftcms/cms/src/services/Matrix.php(354): yii\base\Component->__get('contentTable')
#1 /Users/michael.roper/Sites/v-website/vendor/craftcms/cms/src/services/ProjectConfig.php(786): craft\services\Matrix->handleChangedBlockType(Object(craft\events\ConfigEvent))
#2 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
#3 /Users/michael.roper/Sites/v-website/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
#4 /Users/michael.roper/Sites/v-website/vendor/craftcms/cms/src/services/ProjectConfig.php(486): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#5 /Users/michael.roper/Sites/v-website/vendor/craftcms/cms/src/services/ProjectConfig.php(335): craft\services\ProjectConfig->processConfigChanges('matrixBlockType...', true)
#6 /Users/michael.roper/Sites/v-website/vendor/craftcms/cms/src/migrations/m190108_113000_asset_field_setting_change.php(60): craft\services\ProjectConfig->set('matrixBlockType...', Array)
#7 /Users/michael.roper/Sites/v-website/vendor/craftcms/cms/src/db/Migration.php(56): craft\migrations\m190108_113000_asset_field_setting_change->safeUp()
#8 /Users/michael.roper/Sites/v-website/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#9 /Users/michael.roper/Sites/v-website/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m190108_113000_asset_field_setting_change))
#10 /Users/michael.roper/Sites/v-website/vendor/craftcms/cms/src/services/Updates.php(214): craft\db\MigrationManager->up()
#11 /Users/michael.roper/Sites/v-website/vendor/craftcms/cms/src/console/controllers/MigrateController.php(243): craft\services\Updates->runMigrations(Array)
#12 [internal function]: craft\console\controllers\MigrateController->actionAll()
#13 /Users/michael.roper/Sites/v-website/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /Users/michael.roper/Sites/v-website/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#15 /Users/michael.roper/Sites/v-website/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('all', Array)
#16 /Users/michael.roper/Sites/v-website/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#17 /Users/michael.roper/Sites/v-website/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#18 /Users/michael.roper/Sites/v-website/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('migrate/all', Array)
#19 /Users/michael.roper/Sites/v-website/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#20 /Users/michael.roper/Sites/v-website/craft(43): yii\base\Application->run()
#21 {main}
Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating Craft CMS.'
```

I'm guessing there must be something that has changed in the recent Craft versions that the plugin might need modifications to support?

**Comment by vaughn-taylor** [comment]
I'm glad that I looked at the Issues for this plugin before I installed it. Seems like 3.1 killed some other plugins as well including SuperTable. Hopefully the issue with this plugin will be resolved soon because I'd love to include it in my project.

**Comment by petetak** [comment]
Sorry to hear that.  Now 3.1 is out - have you tried running the migration on that?  I'm caught up in some other work at the moment but I'll try and take a look over the next few days

**Comment by vaughn-taylor** [comment]
@petetak, would running a migration also be required if I were to install the plugin for the first time on CraftCMS 3.1? I assume you were addressing @michaelroper with your comment? I have not yet installed your supercool plugin, but I'd like to start using it. Also, for the sake of clarity, how would one run a migration? I thought all of the technical updating was taken care of by the plugin/cp?

**Comment by michaelroper** [comment]
Hey @petetak - just tried again with v3.1.1, and no dice - still hitting the same error upon migration. If you could take a look, that would be appreciated!

**Comment by michaelroper** [comment]
Update on this - not sure if it's related or just a coincidence, but there was an update overnight to the Neo plugin that I'm also using, and now I'm no longer getting the migration errors complaining about ButtonBox... possibly was complaining because I had ButtonBox fields nested under Neo fields? ¯\_(ツ)_/¯

**Comment by jasonmorehead** [comment]
FWIW, I installed ButtonBox on a site that I just updated to v3.1.1, and it seems to be working fine.

The site doesn't have Neo installed, which might explain why I haven't encountered any errors like the ones that @michaelroper described above.

**Comment by petetak** [comment]
@jasonmorehead @michaelroper thanks for this extra information - this does sound likely.  I have also managed to upgrade on a 3.1.1 with no Neo installed
