### ISSUE TITLE
Linking to bundled images not working

### ISSUE THREAD

**Issue by proimage** [verbb/buttonbox#27]
According to [this page](http://plugins.supercooldesign.co.uk/plugin/button-box/docs/field):

> We have provided you with a set of images for useful things like alignment and columns. These can be found in /buttonbox/resources/images and can be referenced directly from the Image URL column in the field settings using the following pattern: /<cpTrigger>/resources/buttonbox/images/<filename> where <cpTrigger> is whatever the config value cpTrigger is set to (default: ‘admin’) and <filename> is one of the following:

Image | Filename
-- | --
  | align-center.png
  | align-left.png
  | align-right.png
  | grid.png
  | slider.png
  | text-bold.png
  | text-light.png
  | text-box.png
  | text.png
  | col-1.png
  | col-2.png
  | col-3.png
  | text-col-1.png
  | text-col-2.png
  | text-col-3.png

However, the links to the images seem to be broken. I'm in the latest Craft, v3.1.10.

I assume [Asset Bundles](https://docs.craftcms.com/v3/extend/asset-bundles.html) are relevant, but I'm not a programmer and don't know what to make of it.

**Comment by mark-chief** [comment]
The images are also appearing broken for me. Example of URL I am specifying in my fieldtype image column. Using Craft 3.0.15

`/admin/resources/buttonbox/images/align-left.png`

**Comment by tyssen** [comment]
Same here on Craft 3.4.8. My path is exactly the same as mark-chief's.

**Comment by ryanmasuga** [comment]
Anyone ever figure this out? This plugin needs some clear instructions around doing this (Craft 3.4.11) Those instructions above seem to be for Craft 2. We just upgraded a site to Craft 3.4 and all the images are missing. We see them buried deep in the vendor folder...should we be linking to those in some way?

e.g., `/vendor/supercool/buttonbox/resources/images/col-1.png`

**Comment by ryanmasuga** [comment]
For any other poor soul that stumbles along this lonely path...we solved this by copying the `/vendor/supercool/buttonbox/resources/images/` directory, renaming it to “buttonbox’ and putting it at `/assets/img/buttonbox/`. Note that `assets/img` is a directory we already have in our public folder for various other images that we have committed. So the image paths for our buttons look like:

![buttonbox_paths](https://user-images.githubusercontent.com/988995/77795857-9fd75d80-7044-11ea-962b-d1f744b9482e.jpg)

**Comment by engram-design** [comment]
Whilst this is working, agreed that this just needs better documents. Thanks @ryanmasuga

**Comment by engram-design** [comment]
The documentation now reflects this needs to be relative to the `@webroot` of your project.

**Comment by proimage** [comment]
Awesome, thanks! Just to be clear, is that this bit on [this page](http://plugins.supercooldesign.co.uk/plugin/button-box/docs/field)?
![image](https://user-images.githubusercontent.com/1027523/174624696-c2bf8e07-5af7-406d-83c2-fb28b35552c2.png)

**Comment by engram-design** [comment]
For now, documentation is just on the [readme](https://github.com/verbb/buttonbox/blob/craft-4/README.md). You can ignore the Documentation site from Supercool.

None of that applies any more. It's confusing to include `cpTrigger` because it's just not needed. Images just need to be relative to your `@webroot` so Craft can access them - simple as that.
