### ISSUE TITLE
ButtonBox within Supertable not recalling selected buttons

### ISSUE THREAD

**Issue by tigerchick** [verbb/buttonbox#37]
It seems that when a ButtonBox - Buttons field is in a Super Table field and buttons are selected and saved on an entry, when returning to the entry in the backend the selections are lost (all show as default).
Curiously, it does render correctly on the frontend.
Craft: 3.5.16
Super Table 2.6.4
Button Box: 2.0.4

**Comment by engram-design** [comment]
Cannot replicate this on the latest versions. Please comment if this is an issue.

**Comment by engram-design** [comment]
Fixed in [4.2.2](https://github.com/verbb/buttonbox/releases/tag/4.2.2).
