### ISSUE TITLE
Button Box within Supertable within Neo - color value reverts to default upon cloning Neo block

### ISSUE THREAD

**Issue by architchandra** [verbb/buttonbox#38]
We use a _Button Box - Color_ field inside a _Super Table_ field, which in turn is used in a _Neo_ field. We noticed that upon cloning a _Neo_ block, the color in the _Button Box - Color_ field reverts to the default value (rather than sticking to the value from the block that was cloned).

Upon trying out various combinations of fields to isolate the issue, we realized that this was only happening when a _Button Box - Color_ field was inside a _Super Table_ field.

This might also be related to  #37.

Please help with fixing this. Thanks.

#### Versions used
- Craft CMS: 3.4.30
- Neo: 2.7.25
- Super Table: 2.5.4
- Button Box: 2.0.4

**Comment by engram-design** [comment]
Cannot replicate this on the latest versions. Please comment if this is an issue.

**Comment by michaelhue** [comment]
We have the same issue, but without Super Table (just Neo).

**Versions used**
- Craft CMS: 3.7.48
- Neo: 2.13.13
- Button Box: 3.1.0

**Comment by engram-design** [comment]
Fixed in [4.2.2](https://github.com/verbb/buttonbox/releases/tag/4.2.2).
