### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by proimage** [verbb/buttonbox#39]
If so, it would be nice to know. :)

It'd be awesome if the community was able to continue development on this in a collaborate, open-source fashion... it's still the only plugin that does the things it does (icon buttons, etc).

**Comment by bymayo** [comment]
Also wondering the same, mainly because of Craft 4 being released

**Comment by amici-infotech** [comment]
Me too. seems like plugin was last updated in Jul 2019. It has active installs over 1750 and still no clues. Any other alternatives?

**Comment by proimage** [comment]
> Me too. seems like plugin was last updated in Jul 2019. It has active installs over 1750 and still no clues. Any other alternatives?

Hey you. :) Maybe we should code our own? I have a number of feature requests I've posted as issues here over the years. Would be as good a place as any to start out. 🤷‍♂️

**Comment by engram-design** [comment]
Just to chime in here (and we've used this plugin a few times before), we've added this to our [Craft 3 migration project](https://verbb.io/craft-3). If it gets enough votes, we'll migrate this plugin to Craft 4 and continue to work on it, giving it a new home, and keeping it open source.

Of course, don't let that stop you @proimage and @amici-infotech from developing your own!

I'm not sure if @Nav33d or @joshangell wants to comment?

**Comment by proimage** [comment]
> Just to chime in here (and we've used this plugin a few times before), we've added this to our [Craft 3 migration project](https://verbb.io/craft-3). If it gets enough votes, we'll migrate this plugin to Craft 4 and continue to work on it, giving it a new home, and keeping it open source.

Hot dang!! But... 
![image](https://user-images.githubusercontent.com/1027523/168095047-7d4aafe7-7819-4d46-8c31-048e9823d326.png)

I have so many feature requests for Button Box... 🤤

**Comment by engram-design** [comment]
Well, we'd certainly like supercool's blessing for it to find a new home (or for them to state their plans), but according to the [license](https://github.com/supercool/buttonbox/blob/master/LICENSE.md) there's no issue with forking it and continuing development.

**Comment by supercooljames** [comment]
Really sorry for the radio silence, turns out nobody was being notified about the issues on this repo.

We've kinda abandoned the plugin, and haven't yet started any work migrating our plugins to Craft 4 so I'm more than happy for others to pick this up. 

Josh if you want it, consider this my blessing!   😁

**Comment by engram-design** [comment]
Nice one @supercooljames we'll see how much interest we get an go from there!

**Comment by wmdhosting** [comment]
Yes, bring this one.. :)

**Comment by engram-design** [comment]
We've recently acquired this from the Supercool team. Read our [blog post](https://verbb.io/blog/supercool-plugins-have-a-new-home) for more details.

**Comment by proimage** [comment]
Awesome news! _Really_ glad to hear we'll be able to continue using this on client sites for the foreseeable future. :)

Will you be perusing the open issues in this repo, or do we need to recreate them on your repo, or...?

**Comment by amici-infotech** [comment]
> 

Michael seems to be very excited. LOL.. me too.

**Comment by engram-design** [comment]
@proimage We've transferred the repository to Verbb, so the issues will be here. We'll be cleaning up and tackling any urgent items for Craft 3 first, then moving onto Craft 4 shortly afterwards.

**Comment by proimage** [comment]
Great to know, thanks! With that, I think this can be closed. :)
